#!/bin/bash

set -euo pipefail

word=$1
path=$2

cat "$path" |\
perl fix-content.pl "$word" |\
perl fix-encoding.pl "$word" |\
perl bluetext.pl |\
perl greentext.pl |\
perl boldtext.pl |\
perl superscriptize.pl |\
perl subscriptize.pl |\
~/src/w3m/w3m/w3m -graph -X -dump -dump_color -cols 100000 -T text/html -F -r -O UTF-8

# note, this script uses a modified version of w3m (branched from 0.5.3+git20230121-2 version)
# which allows 32k long lines in redered html page.
# this is needed to prevent line wrap even on lines longer than 1024.
# fm.h: #define MAXIMUM_COLS 32000
# and a patch to pass through ANSI color codes.
