#!/bin/bash

set -euo pipefail

comment()
{
	cat
}

path=$1

cat "$path" |\
comment kötőjelek |\
sed -e 's//–/g' |\
comment nem kellő karakterek |\
sed -e 's/  //g' |\
perl bluetext.pl |\
perl superscriptize.pl |\
perl subscriptize.pl |\
~/src/w3m/w3m/w3m -graph -X -dump -cols 100000 -T text/html -F -r -O UTF-8

# note, this script uses a modified version of w3m (branched from 0.5.3+git20230121-2 version)
# which allows 32k long lines in redered html page.
# this is needed to prevent line wrap even on lines longer than 1024.
